name: server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  socket_io: ^1.0.1
  meta: ^1.7.0
  common:
    path: ../common

dev_dependencies:
  lints: ^1.0.0
